In [1]:
import pickle
import numpy as np
import pandas as pd

In [6]:
ohe_sex=pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked=pickle.load(open('models/ohe_embarked.pkl','rb'))
clf=pickle.load(open('models/clf.pkl','rb'))



In [4]:
## data feeding
## rem/age/embarked/sex
test_input=np.array([1,0,0,10.5,31.0,'S','male'],dtype='object').reshape(1,7)

In [5]:
test_input

array([[1, 0, 0, 10.5, 31.0, 'S', 'male']], dtype=object)

In [12]:
sex_df = pd.DataFrame(test_input[:, -1], columns=['Sex'])
test_input_sex=ohe_sex.transform(sex_df)

In [13]:
test_input_sex

array([[1.]])

In [9]:
test_input_embarked=ohe_embarked.transform(test_input[:,5].reshape(1,1))

In [14]:
test_input_embarked

array([[0., 1.]])

In [15]:
test_input_age=test_input[:,4].reshape(1,1)

In [16]:
test_input_age

array([[31.0]], dtype=object)

In [17]:
test_input_transformed=np.concatenate((test_input[:,[0,1,2,3]],test_input_age,test_input_embarked,test_input_sex),axis=1)

In [19]:
test_input_transformed.shape

(1, 8)

In [21]:
clf.predict(test_input_transformed)

array([0])